export const ADMIN_CATEGORY_REQUEST = "ADMIN_CATEGORY_REQUST";
export const ADMIN_CATEGORY_SUCCESS = "ADMIN_CATEGORY_SUCCESS";
export const ADMIN_CATEGORY_FAIL = "ADMIN_CATEGORY_FAIL";


export const NEW_CATEGORY_REQUEST = "NEW_CATEGORY_REQUEST";
export const NEW_CATEGORY_SUCCESS = "NEW_CATEGORY_SUCCESS";
export const NEW_CATEGORY_RESET = "NEW_CATEGORY_RESET";
export const NEW_CATEGORY_FAIL = "NEW_CATEGORY_FAIL";

export const DELTE_CATEGORY_REQUEST = "DELTE_CATEGORY_REQUEST";
export const DELTE_CATEGORY_SUCCESS = "DELTE_CATEGORY_SUCCESS";
export const DELTE_CATEGORY_RESET = "DELTE_CATEGORY_RESET";
export const DELTE_CATEGORY_FAIL = "DELTE_CATEGORY_FAIL";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";

export const ALL_CATEGORY_REQUEST = "ALL_CATEGORY_REQUST";
export const ALL_CATEGORY_SUCCESS = "ALL_CATEGORY_SUCCESS";
export const ALL_CATEGORY_FAIL = "ALL_CATEGORY_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
